#!/bin/bash

# System specific hard coded amdgpu device path
# not doing dynamic lookup because this will run 1x/sec.
# This won't necessarily work on different hardware
# `cat /sys/class/hwmon/hwmon*/name` to get which hwmonX to point to

videoDevice=$(lspci | grep -i "VGA")
if [[ $videoDevice == *"NVIDIA"* ]]; then
  nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits
elif [[ $videoDevice == *"AMD"* ]]; then
  amdDevice="hwmon3"
  cat /sys/class/hwmon/$amdDevice/device/gpu_busy_percent
fi
